#!/bin/bash
set -Eeuo pipefail

# OCLP7 D97GN — read-only collection of MTLCompilerService crash reports
# generated by corrected-Root-Patch accelerated boots on 2026-09-07 23:39 and 23:50.
# NO Root Patch/Restore. NO EFI/NVRAM/framebuffer mutation. NO reboot.

STAMP="$(date +%Y%m%d_%H%M%S)"
OUT="$HOME/Desktop/OCLP7_D97GN_MTLCOMPILERSERVICE_IPS_${STAMP}"
ZIP="$HOME/Desktop/OCLP7_D97GN_MTLCOMPILERSERVICE_IPS_${STAMP}.zip"
mkdir -p "$OUT/reports"
exec > >(tee "$OUT/D97GN_CAPTURE.txt") 2>&1

echo "===== D97GN MTLCOMPILERSERVICE IPS COLLECTION ====="
echo "ROOT_PATCH=NO"
echo "RESTORE=NO"
echo "EFI_MUTATION=NO"
echo "NVRAM_MUTATION=NO"
echo "FRAMEBUFFER_MUTATION=NO"
echo "REBOOT=NO"

/usr/bin/sw_vers
/usr/bin/last reboot > "$OUT/boot_history_full.txt" 2>&1 || true
/usr/bin/head -n 12 "$OUT/boot_history_full.txt" || true

# Known report names observed in D97GL unified log.
cat > "$OUT/known_expected_names.txt" <<'EOF'
MTLCompilerService-2026-09-07-234059.ips
MTLCompilerService-2026-09-07-234100.ips
MTLCompilerService-2026-09-07-234101.ips
MTLCompilerService-2026-09-07-234108.ips
MTLCompilerService-2026-09-07-234109.ips
MTLCompilerService-2026-09-07-234111.000.ips
MTLCompilerService-2026-09-07-234111.ips
MTLCompilerService-2026-09-07-234115.ips
MTLCompilerService-2026-09-07-2351254.ips
MTLCompilerService-2026-09-07-235125.0004.ips
EOF

echo
echo "===== COPY REPORTS ====="
sudo /usr/bin/python3 - "$OUT/reports" "$OUT/report_inventory.tsv" <<'PY'
import pathlib, shutil, sys, hashlib
out=pathlib.Path(sys.argv[1]); inv=pathlib.Path(sys.argv[2])
roots=[
    pathlib.Path('/Library/Logs/DiagnosticReports'),
    pathlib.Path('/Library/Logs/DiagnosticReports/Retired'),
    pathlib.Path.home()/'Library/Logs/DiagnosticReports',
]
# Under sudo, pathlib.home() may be /var/root; add invoking user's home explicitly if available.
import os
sudo_user=os.environ.get('SUDO_USER')
if sudo_user:
    roots.append(pathlib.Path('/Users')/sudo_user/'Library/Logs/DiagnosticReports')
rows=[]; seen=set(); copied=0
for root in roots:
    if not root.exists():
        continue
    try:
        files=list(root.iterdir())
    except Exception as e:
        rows.append((str(root),'ROOT_ERROR',str(e),'','',''))
        continue
    for p in files:
        try:
            if not p.is_file():
                continue
        except Exception:
            continue
        name=p.name
        if not name.startswith('MTLCompilerService-2026-09-07-23') or not name.endswith('.ips'):
            continue
        try:
            st=p.stat()
            key=(name,st.st_size,st.st_mtime_ns)
            if key in seen:
                continue
            seen.add(key)
            dst=out/name
            if dst.exists():
                # preserve duplicates from different locations if content differs
                hsrc=hashlib.sha256(p.read_bytes()).hexdigest()
                hdst=hashlib.sha256(dst.read_bytes()).hexdigest()
                if hsrc==hdst:
                    rows.append((str(p),'DUPLICATE_SAME',str(st.st_size),hsrc,'',str(dst)))
                    continue
                dst=out/(p.stem+'__dup'+str(copied)+p.suffix)
            shutil.copy2(p,dst)
            data=dst.read_bytes(); h=hashlib.sha256(data).hexdigest()
            rows.append((str(p),'COPIED',str(len(data)),h,str(st.st_mtime),str(dst)))
            copied+=1
        except Exception as e:
            rows.append((str(p),'COPY_ERROR',str(e),'','',''))
with inv.open('w') as f:
    f.write('SOURCE\tSTATUS\tBYTES_OR_ERROR\tSHA256\tMTIME_EPOCH\tCOPIED_TO\n')
    for r in rows:
        f.write('\t'.join(r)+'\n')
print(f'D97GN_IPS_COPIED={copied}')
for r in rows:
    print('D97GN_REPORT='+ '\t'.join(r[:4]))
PY

echo
echo "===== INVENTORY ====="
/bin/cat "$OUT/report_inventory.tsv"

COUNT="$(/usr/bin/find "$OUT/reports" -type f -name '*.ips' | /usr/bin/wc -l | /usr/bin/tr -d ' ')"
echo "D97GN_FINAL_IPS_COUNT=$COUNT"

if [[ "$COUNT" -eq 0 ]]; then
    echo "D97GN_STATUS=NO_IPS_FOUND"
    echo "D97GN_REBOOT=NO"
    exit 2
fi

echo
echo "===== REPORT HEADERS ====="
for F in "$OUT"/reports/*.ips; do
    echo "----- $(basename "$F") -----"
    /usr/bin/head -n 8 "$F" 2>/dev/null || true
    echo
 done

echo "===== PACKAGE ====="
/usr/bin/ditto -c -k --sequesterRsrc --keepParent "$OUT" "$ZIP"
SHA="$(/usr/bin/shasum -a 256 "$ZIP" | /usr/bin/awk '{print $1}')"
BYTES="$(/usr/bin/stat -f '%z' "$ZIP")"
echo "D97GN_ZIP=$ZIP"
echo "D97GN_ZIP_SHA256=$SHA"
echo "D97GN_ZIP_BYTES=$BYTES"
echo "D97GN_STATUS=CAPTURE_COMPLETE"
echo "D97GN_REBOOT=NO"
